'use client';
import {FormEvent,useState} from 'react';
import {Sparkles} from 'lucide-react';
import {API} from './account-access';
type Question={question:string;guidance:string};
type Draft={title:string;introduction:string;questions:Question[]};
export default function AIComposer({show}:{show:(message:string)=>void}){
  const [kind,setKind]=useState('worksheet'),[topic,setTopic]=useState(''),[source,setSource]=useState(''),[level,setLevel]=useState('High school'),[count,setCount]=useState(6);
  const [draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[published,setPublished]=useState(false);
  async function generate(event:FormEvent){event.preventDefault();setBusy(true);setError('');setPublished(false);try{
    const response=await fetch(`${API}/ai/compose`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({kind,topic,source,level,questionCount:count})});
    const data=await response.json();if(!response.ok)throw new Error(data.error||'Generation failed');setDraft(data.draft);
  }catch(e){setError(e instanceof Error?e.message:'Generation failed')}finally{setBusy(false)}}
  async function publish(){if(!draft)return;setBusy(true);setError('');try{
    const response=await fetch(`${API}/admin/content`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({kind,...draft})});
    const data=await response.json();if(!response.ok)throw new Error(data.error||'Publish failed');setPublished(true);show('Worksheet published');
  }catch(e){setError(e instanceof Error?e.message:'Publish failed')}finally{setBusy(false)}}
  return <div className="content composer-page"><section className="library-head"><div><p className="eyebrow">AI COMPOSER</p><h2>Build a thoughtful first draft</h2><p>Generate, edit, and review every question before publishing.</p></div></section><div className="composer-grid">
    <form className="panel composer-form" onSubmit={generate}><label>Format<select value={kind} onChange={e=>setKind(e.target.value)}><option value="worksheet">Worksheet</option><option value="discussion_questions">Discussion guide</option></select></label><label>Topic or central question<input value={topic} onChange={e=>setTopic(e.target.value)} required minLength={3} maxLength={300} placeholder="e.g. Rawls and the original position"/></label><div className="composer-row"><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}><option>Middle school</option><option>High school</option><option>Advanced high school</option></select></label><label>Questions<input type="number" min="3" max="12" value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div><label>Source text or notes <small>Optional</small><textarea rows={10} maxLength={12000} value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste an excerpt, meeting theme, or your own notes…"/></label>{error&&<div className="auth-alert" role="alert">{error}</div>}<button className="primary composer-generate" disabled={busy}><Sparkles size={17}/>{busy?'Composing…':draft?'Generate another draft':'Generate draft'}</button><p className="composer-note">AI can make mistakes. Review quotations, citations, and philosophical claims before publishing.</p></form>
    <section className="panel composer-draft">{!draft?<div className="composer-blank"><Sparkles size={28}/><h3>Your draft will appear here</h3><p>Nothing is published automatically.</p></div>:<><div className="panel-title row"><div><span>EDITABLE DRAFT</span></div>{published&&<b className="published-pill">Published</b>}</div><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Introduction<textarea rows={4} value={draft.introduction} onChange={e=>setDraft({...draft,introduction:e.target.value})}/></label><div className="draft-questions">{draft.questions.map((q,i)=><article key={i}><strong>{i+1}</strong><label>Question<textarea rows={3} value={q.question} onChange={e=>setDraft({...draft,questions:draft.questions.map((item,j)=>j===i?{...item,question:e.target.value}:item)})}/></label><label>Teacher guidance<input value={q.guidance} onChange={e=>setDraft({...draft,questions:draft.questions.map((item,j)=>j===i?{...item,guidance:e.target.value}:item)})}/></label></article>)}</div><div className="composer-actions"><button className="secondary" type="button" onClick={()=>setDraft(null)}>Discard draft</button><button className="primary" type="button" disabled={busy||published} onClick={publish}>{published?'Published':'Publish to club'}</button></div></>}</section>
  </div></div>;
}
